# Generated by Django 4.0.5 on 2022-09-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='course',
        ),
        migrations.RemoveField(
            model_name='form',
            name='department',
        ),
        migrations.AddField(
            model_name='form',
            name='job',
            field=models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Data Scientist', 'Data Scientist'), ('Accountant', 'Accountant'), ('Financial Analyst', 'Financial Analyst')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='subject',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Business', 'Business')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
